remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

title: CipherSmith Documentation
description: A secure and powerful password management tool
show_downloads: true
google_analytics:

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Navigation
nav:
  - title: Home
    url: /CipherSmith/
  - title: Quick Start
    url: /CipherSmith/QUICK_START/
  - title: API Reference
    url: /CipherSmith/API_REFERENCE/
  - title: Changelog
    url: /CipherSmith/CHANGELOG/
  - title: Try It!
    url: /CipherSmith/examples/
