remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

title: CipherSmith
tagline: Secure Password Management Made Simple
description: A powerful and secure password management tool built with Python
show_downloads: true
google_analytics:

# Site settings
url: "https://amul-thantharate.github.io"
baseurl: "/CipherSmith"
repository: Amul-Thantharate/CipherSmith
version: "1.3.0"

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/img/logo.png

# Navigation
nav:
  - title: Home
    url: /CipherSmith/
  - title: API Reference
    url: /CipherSmith/api-reference/
  - title: Changelog
    url: /CipherSmith/changelog/
  - title: Try It!
    url: /CipherSmith/examples/
  - title: GitHub
    url: https://github.com/Amul-Thantharate/CipherSmith

# Social links
social:
  github: Amul-Thantharate/CipherSmith
  pypi: ciphersmith

# SEO settings
twitter:
  username: amulthantharate
  card: summary

# Other settings
encoding: UTF-8
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
